[package]
name = "boxxed"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.8.1", features = ["dynamic"] }
bevy_rapier3d = { version = "0.17.0", features = [ "simd-stable", "debug-render" ] }
iyes_loopless = "0.7.1"
leafwing-input-manager = "0.5.2"

[profile.release]
opt-level = 2

[profile.dev.package."*"]
opt-level = 3
