name: Deploy WebAssembly to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Install Trunk 
        uses: jetli/trunk-action@v0.4.0

      - name: Add wasm32 target
        run: rustup target add wasm32-unknown-unknown

      - name: Build using Trunk
        run: trunk build

      - name: Push new build to gh_pages branch
        uses: actions/add-and-commit@v2
        with:
          new_branch: gh_pages
          commit_message: "Update deployment build"


            