name: Deploy WebAssembly to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
            
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown

      - name: Install trunk
        run: >
          wget -qO-
          https://github.com/trunk-rs/trunk/releases/download/v0.18.4/trunk-x86_64-unknown-linux-gnu.tar.gz
          | tar -xzf- && sudo mv trunk /usr/bin/

      - name: Cargo cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: trunk build --release --public-url /boxy/

      - name: Create .nojekyll file
        run: touch ./dist/.nojekyll

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh_pages
          force_orphan: true
          publish_dir: dist/
          enable_jekyll: false