name: Deploy WebAssembly to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: 
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Trunk 
        uses: jetli/trunk-action@v0.4.0
            
      - name: Build using Trunk
        run: trunk build

      - name: Push dist folder to gh-pages branch
        run: git subtree push --prefix dist origin gh-pages
