name: Deploy WebAssembly to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Trunk 
        uses: jetli/trunk-action@v0.4.0

      - name: Add wasm32 target
        run: rustup target add wasm32-unknown-unknown

      - name: Build using Trunk
        run: trunk build

      - name: add dist folder to git
        run: git add dist && git commit -m "dist subtree commit"

      - name: Push dist folder to gh-pages branch
        run: git subtree push --prefix dist origin gh-pages
